-- ============================================
-- Members / Admin 권한 정책 (코드쉴드 보강)
-- Supabase SQL Editor에서 1회 실행
-- ============================================

create table if not exists public.members (
    id bigint generated by default as identity primary key,
    user_id uuid not null unique,
    email text,
    nickname text,
    status text not null default 'pending' check (status in ('pending', 'approved', 'rejected')),
    role text not null default 'member' check (role in ('member', 'admin')),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

alter table public.members
    add column if not exists user_id uuid;
alter table public.members
    add column if not exists email text;
alter table public.members
    add column if not exists nickname text;
alter table public.members
    add column if not exists status text not null default 'pending';
alter table public.members
    add column if not exists role text not null default 'member';
alter table public.members
    add column if not exists created_at timestamptz not null default now();
alter table public.members
    add column if not exists updated_at timestamptz not null default now();

create unique index if not exists members_user_id_uq on public.members(user_id);

alter table public.members enable row level security;

create or replace function public.handle_new_auth_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.members (
    user_id,
    email,
    nickname,
    status,
    role,
    created_at,
    updated_at
  )
  values (
    new.id,
    new.email,
    coalesce(new.raw_user_meta_data->>'nickname', split_part(new.email, '@', 1), '익명'),
    'pending',
    'member',
    now(),
    now()
  )
  on conflict (user_id) do update
  set email = excluded.email,
      updated_at = now();

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_auth_user();

insert into public.members (user_id, email, nickname, status, role, created_at, updated_at)
select
  u.id,
  u.email,
  coalesce(u.raw_user_meta_data->>'nickname', split_part(u.email, '@', 1), '익명'),
  'pending',
  'member',
  now(),
  now()
from auth.users u
left join public.members m on m.user_id = u.id
where m.user_id is null;

create or replace function public.is_admin_user()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.members m
    where m.user_id = auth.uid()
      and m.role = 'admin'
      and m.status = 'approved'
  );
$$;

grant execute on function public.is_admin_user() to authenticated;

drop policy if exists members_self_read on public.members;
drop policy if exists members_insert on public.members;
drop policy if exists members_admin_read on public.members;
drop policy if exists members_self_select on public.members;
create policy members_self_select
on public.members
for select
using (user_id = auth.uid());

drop policy if exists members_self_insert on public.members;
create policy members_self_insert
on public.members
for insert
with check (user_id = auth.uid());

drop policy if exists members_self_update on public.members;
create policy members_self_update
on public.members
for update
using (user_id = auth.uid())
with check (user_id = auth.uid());

drop policy if exists members_admin_select on public.members;
create policy members_admin_select
on public.members
for select
using (public.is_admin_user());

drop policy if exists members_admin_update on public.members;
create policy members_admin_update
on public.members
for update
using (public.is_admin_user())
with check (public.is_admin_user());

drop policy if exists members_admin_delete on public.members;
create policy members_admin_delete
on public.members
for delete
using (public.is_admin_user());
